"""Bullpug Visual Canon Ledger.

Self-populating visual reference library. Every novel location, object,
or scene generated by the Tinkerpug chatbot is stored and used as the
reference the next time someone asks the same question — the community
collectively illustrates the universe, and each contribution locks in
consistency for everyone who follows.

Character subjects (Bullpug, Tinkerpug, and the named Bullpughan cast)
are excluded from this ledger — those have dedicated references in
`services.image_references` and must always use those, never a
community-generated substitute.

────────────────────────────────────────────────────────────────────────
COLLECTION SHAPE (MongoDB: `visual_canon`)
────────────────────────────────────────────────────────────────────────
    {
      "_id": ObjectId,
      "subject_tag": "newpug-city-apartment",      # kebab-case, unique
      "subject_display": "a typical apartment in Newpug City",
      "image_base64": "<base64 string>",           # RAW b64, no data-URL prefix
      "image_mime": "image/jpeg",
      "first_prompt": "what does a typical apartment in Newpug City look like?",
      "request_count": 3,
      "status": "canon",                           # pending | canon | admin_override | retired
      "created_at": ISODate,
      "last_used_at": ISODate,
      "promoted_at": ISODate | None,
      "source": "community",
      "admin_reviewed": false
    }

Status values
  • pending          — generated once or twice, not yet promoted
  • canon            — meets threshold, used as reference on future requests
  • admin_override   — manually promoted by admin (skips threshold)
  • retired          — superseded / rejected, kept as historical record
"""

import logging
import re
from datetime import datetime, timezone
from typing import Optional, List, Dict

from emergentintegrations.llm.chat import LlmChat, UserMessage

from utils.database import db

logger = logging.getLogger(__name__)

# ── Tunables ────────────────────────────────────────────────────────────
CANON_PROMOTION_THRESHOLD = 3        # requests before pending → canon
CANON_MAX_IMAGE_SIZE_MB = 2          # skip storage if generated image larger than this
CANON_COLLECTION = "visual_canon"

# Subject tags that must NEVER live in visual_canon. Named characters
# have dedicated references in `services.image_references` — the
# character pipeline handles them and we never overwrite that anchor
# with a community-generated substitute.
CHARACTER_SUBJECTS = frozenset({
    "bullpug",
    "tinkerpug",
    "ruffus",
    "luna",
    "chargebull",
    "grizzlor",
    "gideon",
    "spirit-of-the-stars",
    "owl-of-oracles",
    "fox-of-forks",
    "cat-of-catalysts",
})


# ── Utilities ───────────────────────────────────────────────────────────
_KEBAB_ALLOWED = re.compile(r"[^a-z0-9-]+")
_MULTI_HYPHEN = re.compile(r"-{2,}")


def _clean_tag(raw: str) -> str:
    """Coerce whatever the LLM emitted into a strict kebab-case tag.

    Never trust the LLM to obey the format instruction perfectly.
    We strip anything not [a-z0-9-], collapse repeated hyphens, and
    trim edge hyphens. Empty result is signalled by empty string.
    """
    if not raw:
        return ""
    lowered = raw.strip().lower()
    # Drop everything after first newline / quote / period to survive
    # the "here's your tag: newpug-city-apartment." style responses.
    for stopper in ("\n", "\r", '"', "'", "`", ".", ":", ";"):
        if stopper in lowered:
            lowered = lowered.split(stopper, 1)[0]
    # Normalise spaces / underscores → hyphens
    lowered = lowered.replace("_", "-").replace(" ", "-")
    lowered = _KEBAB_ALLOWED.sub("", lowered)
    lowered = _MULTI_HYPHEN.sub("-", lowered).strip("-")
    return lowered


def _approx_bytes_from_b64(b64: str) -> int:
    """Estimate decoded bytes from a base64 string. Fast, doesn't decode."""
    if not b64:
        return 0
    # Each base64 char encodes 6 bits → decoded bytes ≈ len * 3 / 4
    return (len(b64) * 3) // 4


def is_character_subject(subject_tag: str) -> bool:
    """Whether a subject tag belongs to the named character exclusion list."""
    return (subject_tag or "").lower() in CHARACTER_SUBJECTS


# ── Subject normalisation ───────────────────────────────────────────────
_NORMALISER_SYSTEM = (
    "You are a subject normaliser for the Bullpughan universe visual "
    "canon. Given a user's image request, return ONLY a short kebab-case "
    "subject tag (2-5 words, lowercase, hyphens only) representing the "
    "visual subject. Do not include character names (Bullpug, Tinkerpug, "
    "Ruffus, Luna, Chargebull, Grizzlor, Gideon, Spirit of the Stars, "
    "Owl of Oracles, Fox of Forks, Cat of Catalysts — these have "
    "dedicated reference images). Focus on locations, objects, and "
    "scenes.\n\n"
    "Examples:\n"
    '- "what does a Newpug City apartment look like" → newpug-city-apartment\n'
    '- "show me the substrate layer" → substrate-layer\n'
    '- "what\'s inside a Snout Scanner" → snout-scanner-interior\n'
    '- "Festival of Barks float" → festival-of-barks-float\n'
    '- "the Genesis Vault door" → genesis-vault-door\n\n'
    "Return ONLY the tag, nothing else."
)


async def normalise_subject(prompt: str, api_key: str, session_id: str = "canon-norm") -> str:
    """Return a kebab-case subject tag for a raw image prompt.

    Cheap single-turn LLM call. If the call fails or returns garbage
    we return an empty string — callers must treat that as "skip canon
    handling for this generation" so a normaliser outage never blocks
    the user's image response.
    """
    if not prompt or not api_key:
        return ""
    try:
        chat = LlmChat(
            api_key=api_key,
            session_id=session_id,
            system_message=_NORMALISER_SYSTEM,
        ).with_model("openai", "gpt-4o")
        raw = await chat.send_message(UserMessage(text=prompt))
        tag = _clean_tag(raw or "")
        # Enforce the 2-5 words rule loosely — at least one hyphen, cap length.
        if not tag:
            return ""
        # Guard against absurd tags — cap at 60 chars, split into segments.
        if len(tag) > 60:
            tag = tag[:60].rstrip("-")
        parts = tag.split("-")
        if len(parts) > 6:
            tag = "-".join(parts[:6])
        return tag
    except Exception as e:
        logger.warning("Subject normalisation failed for prompt %r: %s", prompt[:80], e)
        return ""


# ── Query helpers ───────────────────────────────────────────────────────
async def lookup_canon(subject_tag: str) -> Optional[Dict]:
    """Return the canonical document for a subject, or None.

    Only entries with `status ∈ {canon, admin_override}` are eligible —
    pending and retired entries never anchor a downstream generation.
    Also touches `last_used_at` so admin tooling can surface the hot
    subjects. Failures are swallowed and logged; the caller falls back
    to text-only generation.
    """
    if not subject_tag or is_character_subject(subject_tag):
        return None
    try:
        doc = await db[CANON_COLLECTION].find_one({
            "subject_tag": subject_tag,
            "status": {"$in": ["canon", "admin_override"]},
        })
        if not doc:
            return None
        # Fire-and-forget touch — never block the lookup on the update.
        try:
            await db[CANON_COLLECTION].update_one(
                {"_id": doc["_id"]},
                {"$set": {"last_used_at": datetime.now(timezone.utc).isoformat()}},
            )
        except Exception as e:
            logger.warning("Failed to touch last_used_at on %s: %s", subject_tag, e)
        return doc
    except Exception as e:
        logger.warning("visual_canon lookup failed for %s: %s", subject_tag, e)
        return None


async def record_generation(
    subject_tag: str,
    subject_display: str,
    first_prompt: str,
    image_base64: str,
    image_mime: str,
) -> Optional[Dict]:
    """Create or update the visual_canon document for a subject.

    Rules:
      • If the subject is new → create with status='pending', request_count=1
      • If the subject is pending → increment request_count, refresh the
        candidate image with the newest generation (most recent pending
        generation is the promotion candidate), then check the threshold
        and promote to 'canon' if met.
      • If the subject is already canon or admin_override → increment
        request_count, DO NOT overwrite the stored image. The canon
        image stays stable; the incoming generation was already
        anchored to it via the lookup step.
      • If retired → no-op (kept as historical record only).

    Character subjects are silently skipped — those must never be stored
    here. Overweight images are also skipped so we don't bloat the
    collection with 5MB+ blobs.
    """
    if not subject_tag or is_character_subject(subject_tag):
        return None
    if not image_base64:
        return None
    size_mb = _approx_bytes_from_b64(image_base64) / (1024 * 1024)
    if size_mb > CANON_MAX_IMAGE_SIZE_MB:
        logger.info(
            "Skipping visual_canon store for %s — image %.2fMB exceeds %sMB cap",
            subject_tag, size_mb, CANON_MAX_IMAGE_SIZE_MB,
        )
        return None

    now = datetime.now(timezone.utc).isoformat()
    try:
        existing = await db[CANON_COLLECTION].find_one({"subject_tag": subject_tag})
        if existing is None:
            doc = {
                "subject_tag": subject_tag,
                "subject_display": subject_display or subject_tag.replace("-", " "),
                "image_base64": image_base64,
                "image_mime": image_mime or "image/png",
                "first_prompt": (first_prompt or "")[:400],
                "request_count": 1,
                "status": "pending",
                "created_at": now,
                "last_used_at": now,
                "promoted_at": None,
                "source": "community",
                "admin_reviewed": False,
            }
            await db[CANON_COLLECTION].insert_one(doc)
            logger.info("visual_canon: created pending entry for %s", subject_tag)
            return doc

        status = existing.get("status", "pending")
        new_count = int(existing.get("request_count", 0) or 0) + 1

        if status == "retired":
            # Historical record — do not touch beyond a count bump so admins
            # can see if a retired subject is trending again.
            await db[CANON_COLLECTION].update_one(
                {"_id": existing["_id"]},
                {"$set": {"request_count": new_count, "last_used_at": now}},
            )
            return None

        if status in ("canon", "admin_override"):
            # Canon image stays stable — only bump the counter + touch.
            await db[CANON_COLLECTION].update_one(
                {"_id": existing["_id"]},
                {"$set": {"request_count": new_count, "last_used_at": now}},
            )
            return {**existing, "request_count": new_count, "last_used_at": now}

        # status == "pending" — refresh candidate image, then check promotion.
        update: Dict = {
            "image_base64": image_base64,
            "image_mime": image_mime or "image/png",
            "request_count": new_count,
            "last_used_at": now,
        }
        promoted = False
        if new_count >= CANON_PROMOTION_THRESHOLD:
            update["status"] = "canon"
            update["promoted_at"] = now
            promoted = True
        await db[CANON_COLLECTION].update_one(
            {"_id": existing["_id"]},
            {"$set": update},
        )
        if promoted:
            logger.info(
                "visual_canon: promoted %s to canon (request_count=%d)",
                subject_tag, new_count,
            )
        return {**existing, **update}
    except Exception as e:
        logger.warning("visual_canon record_generation failed for %s: %s", subject_tag, e)
        return None


# ── Admin queries ───────────────────────────────────────────────────────
_LIST_PROJECTION = {
    "_id": 0,
    "subject_tag": 1,
    "subject_display": 1,
    "image_base64": 1,
    "image_mime": 1,
    "first_prompt": 1,
    "request_count": 1,
    "status": 1,
    "created_at": 1,
    "last_used_at": 1,
    "promoted_at": 1,
    "source": 1,
    "admin_reviewed": 1,
}


async def get_all_canon(skip: int = 0, limit: int = 50) -> List[Dict]:
    """Paginated list of canon entries (status ∈ {canon, admin_override})."""
    skip = max(0, int(skip or 0))
    limit = max(1, min(200, int(limit or 50)))
    try:
        cursor = (
            db[CANON_COLLECTION]
            .find(
                {"status": {"$in": ["canon", "admin_override"]}},
                _LIST_PROJECTION,
            )
            .sort("last_used_at", -1)
            .skip(skip)
            .limit(limit)
        )
        return await cursor.to_list(length=limit)
    except Exception as e:
        logger.warning("visual_canon get_all_canon failed: %s", e)
        return []


async def get_pending(skip: int = 0, limit: int = 50) -> List[Dict]:
    """Paginated list of pending entries awaiting promotion."""
    skip = max(0, int(skip or 0))
    limit = max(1, min(200, int(limit or 50)))
    try:
        cursor = (
            db[CANON_COLLECTION]
            .find({"status": "pending"}, _LIST_PROJECTION)
            .sort("request_count", -1)
            .skip(skip)
            .limit(limit)
        )
        return await cursor.to_list(length=limit)
    except Exception as e:
        logger.warning("visual_canon get_pending failed: %s", e)
        return []


# ── Admin mutations ─────────────────────────────────────────────────────
async def admin_override(subject_tag: str, image_base64: Optional[str] = None,
                         image_mime: Optional[str] = None) -> Optional[Dict]:
    """Force-promote a subject to canon, optionally replacing the image.

    • If `image_base64` is provided, it overwrites the stored image and
      status becomes 'admin_override' (admin-curated canon).
    • Otherwise the current pending image is promoted in place (status
      becomes 'canon' with `admin_reviewed=True`).
    Returns the updated document, or None if the subject doesn't exist.
    """
    if not subject_tag:
        return None
    now = datetime.now(timezone.utc).isoformat()
    try:
        existing = await db[CANON_COLLECTION].find_one({"subject_tag": subject_tag})
        if not existing:
            return None
        update: Dict = {
            "promoted_at": now,
            "last_used_at": now,
            "admin_reviewed": True,
        }
        if image_base64:
            size_mb = _approx_bytes_from_b64(image_base64) / (1024 * 1024)
            if size_mb > CANON_MAX_IMAGE_SIZE_MB:
                logger.warning(
                    "admin_override rejected: image %.2fMB exceeds %sMB cap for %s",
                    size_mb, CANON_MAX_IMAGE_SIZE_MB, subject_tag,
                )
                return None
            update["image_base64"] = image_base64
            update["image_mime"] = image_mime or existing.get("image_mime", "image/png")
            update["status"] = "admin_override"
        else:
            update["status"] = "canon"
        await db[CANON_COLLECTION].update_one(
            {"_id": existing["_id"]},
            {"$set": update},
        )
        merged = {**existing, **update}
        merged.pop("_id", None)
        logger.info("visual_canon: admin_override applied to %s (status=%s)",
                    subject_tag, update["status"])
        return merged
    except Exception as e:
        logger.warning("visual_canon admin_override failed for %s: %s", subject_tag, e)
        return None


async def retire(subject_tag: str) -> Optional[Dict]:
    """Retire a canon entry — removes it from the active reference pool.

    Kept in the DB with status='retired' so we don't lose history and so
    the same subject_tag can be re-promoted later if a better generation
    comes along.
    """
    if not subject_tag:
        return None
    now = datetime.now(timezone.utc).isoformat()
    try:
        result = await db[CANON_COLLECTION].find_one_and_update(
            {"subject_tag": subject_tag},
            {"$set": {"status": "retired", "last_used_at": now, "admin_reviewed": True}},
            projection=_LIST_PROJECTION,
            return_document=True,
        )
        # motor's default is ReturnDocument.BEFORE. We just want any doc back.
        if not result:
            existing = await db[CANON_COLLECTION].find_one(
                {"subject_tag": subject_tag}, _LIST_PROJECTION
            )
            return existing
        return result
    except Exception as e:
        logger.warning("visual_canon retire failed for %s: %s", subject_tag, e)
        return None


async def discard(subject_tag: str) -> bool:
    """Delete a pending entry entirely. Used by admin to reject a bad
    first generation before it gets promoted. Never used on canon
    entries — those must be retired, not deleted, so the history stays."""
    if not subject_tag:
        return False
    try:
        result = await db[CANON_COLLECTION].delete_one({
            "subject_tag": subject_tag,
            "status": "pending",
        })
        return result.deleted_count > 0
    except Exception as e:
        logger.warning("visual_canon discard failed for %s: %s", subject_tag, e)
        return False
